#include <fstream>

#ifndef COMPUTER_GRAPHIC_PROJECT_SRC_FILEHANDLER_FILEHANDLER_H_
#define COMPUTER_GRAPHIC_PROJECT_SRC_FILEHANDLER_FILEHANDLER_H_


class FileHandler {
 private:

};

#endif //COMPUTER_GRAPHIC_PROJECT_SRC_FILEHANDLER_FILEHANDLER_H_
